stages:
  - build

build:
  stage: build
  image: openjdk:17-jdk-slim
  script:
    - echo "Building APK"
    - apt-get update && apt-get install -y wget unzip
    - mkdir -p app/libs
    - wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmd.zip
    - mkdir -p android-sdk/cmdline-tools
    - unzip -q cmd.zip -d android-sdk/cmdline-tools
    - mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
    - export ANDROID_HOME=$PWD/android-sdk
    - export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
    - yes | sdkmanager --licenses
    - yes | sdkmanager "platforms;android-35" "build-tools;35.0.0"
    - curl -L -o app/libs/libv2ray.aar "https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray.aar"
    - chmod +x gradlew
    - ./gradlew assembleDebug --no-daemon
  artifacts:
    paths:
      - app/build/outputs/apk/debug/*.apk
    expire_in: 1 week
